### ISSUE TITLE
The scene lags a lot, mainly when a new segment spawns

### ISSUE THREAD

**Issue by keanine** [AlisterGreg/ProjectMinorMiners#21]
Steps to reproduce:
1. Start the build
2. Wait for a level segment to spawn

Consequences:
The game feels unplayable because of both how slow yet inconsistent the movement is.

Expected Behaviour:
The game should run at a fluid and consistent 60fps.

Attachments:
[BUILD-LagDemonstration.zip](https://github.com/AlisterGreg/ProjectMinorMiners/files/862310/BUILD-LagDemonstration.zip)

**Comment by AlisterGreg** [comment]
This is now fixed!
