### ISSUE TITLE
Main Menu not recieving updates.

### ISSUE THREAD

**Issue by HarmedTwins** [AlisterGreg/ProjectMinorMiners#25]
Steps to reproduce:
1. Go into the main game by hitting the 'Play Game' button.
2. Die and get put back into the main menu.
Proof of no updates:
3. Click on the 'Upgrades' button, then click on any item you cannot buy (cannot afford/already at max).

Expected outcome:
Error text to appear then slowly fade away via the main menu update.

Actual outcome:
Error text appears and doesn't fade with no update being called.

Consequences:
Main menu not being updated, any important functions in the main menu update will not occur if you've already been into the main game.

Temporary fix:
Error text now disappears when closing the shop window.
![errortextbug](https://cloud.githubusercontent.com/assets/16520920/24362088/9c4607a8-1303-11e7-8062-13d531d183f1.gif)

**Comment by AlisterGreg** [comment]
Fixed The Issue
