### ISSUE TITLE
UI Font to small

### ISSUE THREAD

**Issue by rhino1181** [AlisterGreg/ProjectMinorMiners#9]
Issue: The font size for the UI is too small
Expected: The font size should scale to fit the screen and be readable
Phone used: Samsung Galaxy S7

![17431039_10207509913779827_1310765981_o](https://cloud.githubusercontent.com/assets/13394378/24111066/2d4e719e-0d8d-11e7-8212-5ee869dc139e.png)

**Comment by AlisterGreg** [comment]
This Should be Fixed now
